### ISSUE TITLE
Bug: traceback of pylint on branch master

### ISSUE THREAD

**Issue by guoang** [python-mode/python-mode#863]
traceback detail:

```
2: 'check code'
1520427154 ['pyflakes', 'pep8', 'mccabe'] []
Error detected while processing function pymode#buffer_post_write[10]..pymode#lint#check:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/guoang/.vim/plugged/python-mode/pymode/lint.py", line 46, in code_check
    options.linters_params['pylint']['clear_cache'] = True
KeyError: 'pylint'
```
It happens when `'pylint'` is not in `g:pymode_lint_checkers`, leads to code checking failure.

**Comment by fmv1992** [comment]
Hey @guoang,

Thanks for your update on this bug. I know this is a bit of a hassle but can you please submit the output of your bug report as suggested in our [troubleshooting session](https://github.com/python-mode/python-mode#troubleshootingdebugging)?

I could not reproduce your bug. Removed the linter and had no troubles whatsoever.

Best,

**Comment by fmv1992** [comment]
Actually I missed the point that you were referring to the master branch.

Our master branach is super outdated. I should point it out in our documentation.

Do not close this issue! : )

**Comment by mrbig033** [comment]
I have the same problem. Installed it with vim-plug.
```
Error detected while processing function pymode#buffer_post_write[10]..pymode#lint#check[11]..provider#python3#Call:   
line   18:                                                                                                             
Traceback (most recent call last):                                                                                     
  File "<string>", line 1, in <module>                                                                                 
  File "/home/BigHome/Dropbox/dotfiles/nvim/python/python-plugins/python-mode/pymode/lint.py", line 46, in code_check  
    options.linters_params['pylint']['clear_cache'] = True                                                             
KeyError: 'pylint' 
```

**Comment by diraol** [comment]
> I have the same problem. Installed it with vim-plug. NVIM v0.2.3-820-g9cefd83cc. Build type: RelWithDebInfo. MX-Linux 17.

This was addressed on #864 (and is already fixed).

**Comment by amireldor** [comment]
No, this was __not addressed__ in #864 and it was **not fixed**. In the mentioned issue the "solution" was to use pathogen instead of vim-plug. You can't force your users to a specific plugin manager.

**Comment by amireldor** [comment]
With vim-plug, I specified the 'develop' branch and now stuff works.
 
    Plug 'python-mode/python-mode', { 'branch': 'develop' }

**Comment by diraol** [comment]
Hi @amireldor I tought it was fixed, my mistake. I don't think you need to be that aggressive ... I'm not trying to force anyone to nothing ok? Still, please consider that I'm just a volunteer on the project.

I'm glad you could make it work with your desired tools and it would be nice if you send us a PullRequest with the proper improvement on the project documentation.

If you do so, please try to "link" this issue and also #864 on the commit message in order to keep the correct track of information.

**Comment by amireldor** [comment]
@diraol please accept my apology. Sometimes when I use Vim too much without looking out of the window at the birds I forget my manners. I'll do my best to make a PR today. Thanks.

**Comment by diraol** [comment]
No problem @amireldor, and thanks for the PR! Welcome to the project! ;)
