### ISSUE TITLE
Error processing lint.vim

### ISSUE THREAD

**Issue by gperezcarellan** [python-mode/python-mode#961]
Hi, here is my debugg file, any help is appreciated.

-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-11-15 00:19:44 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.vim/bundle/python-mode/debugvimrc.vim
  2: /usr/share/vim/vim80/plugin/getscriptPlugin.vim
  3: /usr/share/vim/vim80/plugin/gzip.vim
  4: /usr/share/vim/vim80/plugin/logiPat.vim
  5: /usr/share/vim/vim80/plugin/manpager.vim
  6: /usr/share/vim/vim80/plugin/matchparen.vim
  7: /usr/share/vim/vim80/plugin/netrwPlugin.vim
  8: /usr/share/vim/vim80/plugin/rrhelper.vim
  9: /usr/share/vim/vim80/plugin/spellfile.vim
 10: /usr/share/vim/vim80/plugin/tarPlugin.vim
 11: /usr/share/vim/vim80/plugin/tohtml.vim
 12: /usr/share/vim/vim80/plugin/vimballPlugin.vim
 13: /usr/share/vim/vim80/plugin/zipPlugin.vim
 14: ~/.vim/bundle/python-mode/plugin/pymode.vim
 15: ~/.vim/bundle/python-mode/autoload/pymode.vim
 16: /usr/share/vim/vim80/filetype.vim
 17: /usr/share/vim/vim80/ftplugin.vim
 18: /usr/share/vim/vim80/ftplugin/python.vim
 19: ~/.vim/bundle/python-mode/ftplugin/python/pymode.vim
 20: ~/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim
 21: ~/.vim/bundle/python-mode/autoload/pymode/breakpoint.vim
 22: ~/.vim/bundle/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
Error detected while processing /home/guillermo/.vim/bundle/python-mode/ftplugin/python/pymode.vim:
line  250:
Interrupted
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/guillermo/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/guillermo/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/guillermo/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/guillermo/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/guillermo/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/guillermo/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/guillermo/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/guillermo/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/guillermo/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/guillermo/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_spec(packageName)
Error detected while processing /home/guillermo/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: module 'vim' has no attribute 'find_spec'

**Comment by cchampio** [comment]
I seem to be getting the same lint error. I cannot tell whether it is exactly like Guillerm097 but it is very close. Any help much appreciated and let me know if you need further information or would like debug output from one of the other branches.

- New install of Ubuntu Desktop 18.04.1 LTS
- Using vim-plug plugin manager
- Vim 8.0 with +python3
- I do have 'let g:pymode_python = 'python3'' in my vimrc (above the vim-plug Plug commands).

I have tried the following branches and I get errors on each. 

Plug 'python-mode/python-mode', { 'branch': 'develop' } //lint error
""Plug 'diraol/python-mode', { 'branch': 'develop' } //six error
""Plug 'diraol/python-mode', { 'branch': 'fix_six_import' } //lint error

Using 'python-mode/python-mode' the output of the pymode debug file is: 

 

-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-11-25 09:28:22 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.vim/plugged/python-mode/debugvimrc.vim
  2: /usr/share/vim/vim80/plugin/getscriptPlugin.vim
  3: /usr/share/vim/vim80/plugin/gzip.vim
  4: /usr/share/vim/vim80/plugin/logiPat.vim
  5: /usr/share/vim/vim80/plugin/manpager.vim
  6: /usr/share/vim/vim80/plugin/matchparen.vim
  7: /usr/share/vim/vim80/plugin/netrwPlugin.vim
  8: /usr/share/vim/vim80/plugin/rrhelper.vim
  9: /usr/share/vim/vim80/plugin/spellfile.vim
 10: /usr/share/vim/vim80/plugin/tarPlugin.vim
 11: /usr/share/vim/vim80/plugin/tohtml.vim
 12: /usr/share/vim/vim80/plugin/vimballPlugin.vim
 13: /usr/share/vim/vim80/plugin/zipPlugin.vim
 14: ~/.vim/plugged/python-mode/plugin/pymode.vim
 15: ~/.vim/plugged/python-mode/autoload/pymode.vim
 16: /usr/share/vim/vim80/filetype.vim
 17: /usr/share/vim/vim80/ftplugin.vim
 18: /usr/share/vim/vim80/ftplugin/python.vim
 19: ~/.vim/plugged/python-mode/ftplugin/python/pymode.vim
 20: ~/.vim/plugged/python-mode/autoload/pymode/virtualenv.vim
 21: ~/.vim/plugged/python-mode/autoload/pymode/breakpoint.vim
 22: ~/.vim/plugged/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
551c9d473f269d3b1ef7354506af4485bb88ba2c
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/cchampio/.vim/plugged/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/cchampio/.vim/plugged/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/cchampio/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/cchampio/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/cchampio/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/cchampio/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/cchampio/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/cchampio/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/cchampio/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/cchampio/.vim/plugged/python-mode/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_spec(packageName)
Error detected while processing /home/cchampio/.vim/plugged/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: module 'vim' has no attribute 'find_spec'

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"program.py" 10L, 60C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-11-25 09:28:22 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC

  3  
-------------------------------------------------------------------------------
pymode debug msg 7: Session history:
      #  cmd history
      1  messages
>     2  q


vim -i NONE -u ~/.vim/plugged/python-mode/debugvimrc.vim program.py

**Comment by AntonOfTheWoods** [comment]
I had this error after updating all my plugins a week or so ago. I just updated again and the problem now appears to be fixed. YMMV... @cchampio

**Comment by diraol** [comment]
Folks, can you all try to update your codebase and see if it works now, please?

**Comment by racterub** [comment]
@diraol 
I'm on MacOS 10.14.1, Macvim, with `- python` `+ python3` support.
I've reinstalled python-mode
vim version:
```
[~] $ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  5 2018 21:23:16)
macOS version
Included patches: 1-280
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
+autochdir         +float             +mouse_xterm       +terminal
-autoservername    +folding           +multi_byte        +terminfo
+balloon_eval      -footer            +multi_lang        +termresponse
+balloon_eval_term +fork()            -mzscheme          +textobjects
+browse            +fullscreen        +netbeans_intg     +timers
++builtin_terms    -gettext           +num64             +title
+byte_offset       -hangul_input      +odbeditor         +toolbar
+channel           +iconv             +packages          +transparency
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               +ruby              +writebackup
+dialog_con_gui    +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       -xpm
-ebcdic            +mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
```
python-mode log
```
03:05 $ cat /var/folders/dx/d8cq9qgj3tl375567_hhycm40000gn/T/pymode_debug_file.txt

-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-12-06 03:04:33 with file /var/folders/dx/d8cq9qgj3tl375567_hhycm40000gn/T/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Darwin
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.vim/bundle/python-mode/debugvimrc.vim
  2: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/getscriptPlugin.vim
  3: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/gzip.vim
  4: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/logiPat.vim
  5: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/manpager.vim
  6: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/matchparen.vim
  7: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/netrwPlugin.vim
  8: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/rrhelper.vim
  9: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/spellfile.vim
 10: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/tarPlugin.vim
 11: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/tohtml.vim
 12: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/vimballPlugin.vim
 13: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/plugin/zipPlugin.vim
 14: ~/.vim/bundle/python-mode/plugin/pymode.vim
 15: ~/.vim/bundle/python-mode/autoload/pymode.vim
 16: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/filetype.vim
 17: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/ftplugin.vim
 18: /usr/local/Cellar/macvim/8.1-151/MacVim.app/Contents/Resources/vim/runtime/ftplugin/python.vim
 19: ~/.vim/bundle/python-mode/ftplugin/python/pymode.vim
 20: ~/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim
 21: ~/.vim/bundle/python-mode/autoload/pymode/breakpoint.vim
 22: ~/.vim/bundle/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /var/folders/dx/d8cq9qgj3tl375567_hhycm40000gn/T/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled
pymode_virtualenv_path
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit:
d6f76c4fafb27ad64da64461c46e4e70c47c01ff
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/macintosh/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/macintosh/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 50, in <module>
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/macintosh/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/macintosh/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/macintosh/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/macintosh/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/macintosh/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/macintosh/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/macintosh/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/macintosh/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_module(packageName)
Error detected while processing /Users/macintosh/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: module 'vim' has no attribute 'find_module'
```

**Comment by cchampio** [comment]
Fixed.
I updated branch python-mode/python-mode and it seems to be working magnificently. Very excited, thank you!

**Comment by dbeniamine** [comment]
Hi,

On Debian Buster with vim 8.1 and the last pymode and submodules, I still have the same error message as @racterub:

```
"/path/to/pythonstuff.py" 81L, 2091C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-12-07 16:45:02 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
  mode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled
pymode_virtualenv_path
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit:
d6f76c4fafb27ad64da64461c46e4e70c47c01ff
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/david/Documents/Conf/vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/david/Documents/Conf/vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 50, in <module>
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/david/Documents/Conf/vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/david/Documents/Conf/vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/david/Documents/Conf/vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/david/Documents/Conf/vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/david/Documents/Conf/vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/david/Documents/Conf/vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/david/Documents/Conf/vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/david/Documents/Conf/vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_module(packageName)
Press ENTER or type command to continue
Error detected while processing /home/david/Documents/Conf/vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: module 'vim' has no attribute 'find_module'
```

Vim version :

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 28 2018 01:38:28)
Included patches: 1-549
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua               +ruby              +writebackup
+dialog_con_gui    +menu              +scrollbind        +X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       +xpm
-ebcdic            +mouseshape        +statusline        +xsmp_interact
+emacs_tags        +mouse_dec         -sun_workshop      +xterm_clipboard
+eval              +mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-MVNMrg/vim-8.1.0549=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.28/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm
```

**Comment by joergsch** [comment]
Looks like this is due to vim 8.1.0201
https://github.com/vim/vim/commit/79a494d5e2f97c10e74f92ea529552623c314422
https://bugs.archlinux.org/task/60557
gist: find_module is no longer available in vim, find_spec has to be used instead

**Comment by javiroman** [comment]
I'm getting the same error with 8.1.549-1.fc29 (Fedora).

```
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-12-10 10:18:00 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.vim/bundle/python-mode/debugvimrc.vim
  2: /usr/share/vim/vimfiles/plugin/cctree.vim
  3: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
  4: /usr/share/vim/vim81/plugin/gzip.vim
  5: /usr/share/vim/vim81/plugin/logiPat.vim
  6: /usr/share/vim/vim81/plugin/manpager.vim
  7: /usr/share/vim/vim81/plugin/matchparen.vim
  8: /usr/share/vim/vim81/plugin/netrwPlugin.vim
  9: /usr/share/vim/vim81/plugin/rrhelper.vim
 10: /usr/share/vim/vim81/plugin/spellfile.vim
 11: /usr/share/vim/vim81/plugin/tarPlugin.vim
 12: /usr/share/vim/vim81/plugin/tohtml.vim
 13: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 14: /usr/share/vim/vim81/plugin/zipPlugin.vim
 15: ~/.vim/bundle/python-mode/plugin/pymode.vim
 16: ~/.vim/bundle/python-mode/autoload/pymode.vim
 17: /usr/share/vim/vim81/filetype.vim
 18: /usr/share/vim/vim81/ftplugin.vim
 19: /usr/share/vim/vim81/ftplugin/python.vim
 20: ~/.vim/bundle/python-mode/ftplugin/python/pymode.vim
 21: ~/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim
 22: ~/.vim/bundle/python-mode/autoload/pymode/breakpoint.vim
 23: ~/.vim/bundle/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
d6f76c4fafb27ad64da64461c46e4e70c47c01ff
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jroman/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jroman/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jroman/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3092, in <module>
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jroman/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3078, in _call_aside
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jroman/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in _initialize_master_working_set
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jroman/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jroman/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3117, in <lambda>
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jroman/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2636, in activate
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    declare_namespace(pkg)
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jroman/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2227, in declare_namespace
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    _handle_ns(packageName, path_item)
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jroman/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 2173, in _handle_ns
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    loader = importer.find_module(packageName)
Error detected while processing /home/jroman/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
AttributeError: module 'vim' has no attribute 'find_module'

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"gridexecutor.py" 100L, 3018C
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-12-10 10:18:00 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}

  3 # Copyright (C) 2015 Javi Roman <javiroman@apache.org>
-------------------------------------------------------------------------------
pymode debug msg 7: Session history:
      #  cmd history
      1  messages
>     2  qa
```

**Comment by racterub** [comment]
> Looks like this is due to vim 8.1.0201
> [vim/vim@79a494d](https://github.com/vim/vim/commit/79a494d5e2f97c10e74f92ea529552623c314422)
> [bugs.archlinux.org/task/60557](https://bugs.archlinux.org/task/60557)
> gist: find_module is no longer available in vim, find_spec has to be used instead

@joergsch 's solution fixes the issue on my side 👍 

But if it changed to `find_spec` will issue #958 happen again ?

**Comment by javiroman** [comment]
More info here:
```
$ git clone --recursive https://github.com/python-mode/python-mode.git
$ cd python-mode
$ git branch
* develop
$ grep -r find_module .                                                                                                                        
./autoload/pymode/breakpoint.vim:    from imp import find_module                                                                                                             
./autoload/pymode/breakpoint.vim:            return find_module(module_name)                                                                                                 
./pymode/libs/logilab-common-1.4.1/ChangeLog:        change of imp.find_module wrt builtin modules (#137244)                                                                 
./pymode/libs/logilab-common-1.4.1/ChangeLog:    * change implementation of modutils.load_module_from_name (use find_module                                                  
./pymode/libs/logilab-common-1.4.1/logilab/common/modutils.py:from imp import find_module, load_module, C_BUILTIN, PY_COMPILED, PKG_DIRECTORY                                
./pymode/libs/logilab-common-1.4.1/logilab/common/modutils.py:            mp_file, mp_filename, mp_desc = find_module(part, path)                                            
./pymode/libs/logilab-common-1.4.1/logilab/common/modutils.py:        find_module(modname.split('.')[0], [from_file])                                                        
./pymode/libs/logilab-common-1.4.1/logilab/common/modutils.py:            if importer.find_module(modpath[0]):                                                               
./pymode/libs/logilab-common-1.4.1/logilab/common/modutils.py:                if not importer.find_module('/'.join(modpath)):                                                
./pymode/libs/logilab-common-1.4.1/logilab/common/modutils.py:        # find_module later doesn't like                                                                       
./pymode/libs/logilab-common-1.4.1/logilab/common/modutils.py:        # take care to changes in find_module implementation wrt builtin modules                               
./pymode/libs/logilab-common-1.4.1/logilab/common/modutils.py:        # >>> imp.find_module('posix')                                                                         
./pymode/libs/logilab-common-1.4.1/logilab/common/modutils.py:        # >>> imp.find_module('posix')                                                                         
./pymode/libs/logilab-common-1.4.1/logilab/common/modutils.py:            _, mp_filename, mp_desc = find_module(modname, path)  
[...]
```

**Comment by diraol** [comment]
As this error is happening a lot, I'm centralizing all discussions under #972 .

@javiroman , @racterub @joergsch @dbeniamine , Testers and Contributions are welcome! =)
